#!/bin/bash

declare -a utils=(
  'args'
   'fs'
   'io'
   'os'
   'proxy'
   'strings'
   'system'
   'vcs'
)

for i in ${utils[@]}; do
    [ -f "$(dirname $BASH_SOURCE[0])/utils/utils_${i}" ] \
      && source "$(dirname $BASH_SOURCE[0])/utils/utils_${i}"
done