#!/usr/bin/env bash

# ----------------------------------------------------------------------
# | Navigation                                                         |
# ----------------------------------------------------------------------

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cd..='cd ..'

# ----------------------------------------------------------------------
# | Network                                                            |
# ----------------------------------------------------------------------

alias ip='dig +short myip.opendns.com @resolver1.opendns.com'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ "$os" == 'osx' ]; then
    alias local-ip='ipconfig getifaddr en1'
elif [ "$os" == 'ubuntu' ]; then
    alias local-ip="ifconfig | \
                    | grep 'inet addr' \
                    | grep -v '127.0.0.1' \
                    | cut -d: -f2 \
                    | cut -d' ' -f1"
fi

# ----------------------------------------------------------------------
# | Package Managers                                                   |
# ----------------------------------------------------------------------

# OS specific package managers

if [ "$os" == 'osx' ]; then

    # Homebrew
    if command -v 'brew' &> /dev/null; then
        alias brewd='brew doctor'
        alias brewi='brew install'
        alias brewr='brew uninstall'
        alias brews='brew search'
        alias brewu='brew update \
                      && brew upgrade --all \
                      && brew cleanup \
                      && brew cask cleanup'
    fi

elif [ "$os" == 'ubuntu' ]; then

    # Advanced Packaging Tool
    alias apti='sudo apt-get install'
    alias aptr='sudo apt-get remove'
    alias apts='sudo apt-cache search'
    alias aptu='sudo apt-get update \
                 && sudo apt-get upgrade'

fi

# ----------------------------------------------------------------------
# | Shorter Commands                                                   |
# ----------------------------------------------------------------------

alias :q='exit'
alias c='clear'
alias ch='history -c && > ~/.bash_history'
alias e='vim'
alias g='git'
alias ll='ls -l'
alias m='man'
alias map='xargs -n1'
alias q='exit'
alias rm='rm -rf'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Lock screen

if [ "$os" == 'osx' ]; then
    alias afk='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'
elif [ "$os" == 'ubuntu' ]; then
    alias akf='gnome-screensaver-command --lock'
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Open

if [ "$os" == 'osx' ]; then
    alias o='open'
elif [ "$os" == 'ubuntu' ]; then
    alias o='xdg-open'
fi

# ----------------------------------------------------------------------

# Unset anything that just pollutes the global space

unset OS
