#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Source bash_utils - I would like all util functions available in any
# bash script executed.

[ -f "~/.bash_utils" ] \
  && source ~/.bash_utils
