#!/usr/bin/env bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Definitions

enable_programmable_completion() {

    local OS="$(get_os)"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Enable programmable completion features
    # http://tldp.org/LDP/abs/html/tabexpansion.html

    if [ "$OS" == 'osx' ]; then

        if [ -f $(brew --prefix)/share/bash-completion/bash_completion ]; then

            # Use `bash-completion` 2.x
            source $(brew --prefix)/share/bash-completion/bash_completion

            # Make bash complete the `g` alias, just like it does `git`
            complete -o default -o nospace -F _git g
        fi

    elif [ "$OS" == 'ubuntu' ]; then

        if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
            source /etc/bash_completion
        fi

    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    [ -f "$NVM_DIR/bash_completion" ] \
        && source $NVM_DIR/bash_completion

}

source_bash_files() {

    local file=''
    local i=''

    declare -r -a FILES_TO_SOURCE=(
        'bash_utils'
        'bash_aliases'
        'bash_exports'
        'bash_functions'
        'bash_options'
        'bash_prompt'
        'bash_extra'
        'bash_login'
        'bash.local' # for local settings that should
                     # not be under version control
        'bash.local.proxy' # for local proxy settings (do not verson control)
    )

    for i in ${!FILES_TO_SOURCE[*]}; do
        file="$HOME/.${FILES_TO_SOURCE[$i]}"
        [ -r "$file" ] && source "$file"
    done

}

bash_profile() {
    source_bash_files

    enable_programmable_completion

    # Clear system messages (e.g.: system copyright notice, the
    # date and time of the last login, the message of the day, etc.)

    # clear
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Main

bash_profile

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Cleanup

unset enable_programmable_completion
unset bash_profile
unset source_bash_files
