#!/bin/bash

if [[ "$(uname -s)" == "Darwin" ]]; then
    trueSource="$(readlink $BASH_SOURCE)"
else
    trueSource="$(readlink -f $BASH_SOURCE)"
fi

if [ -d "$trueSource" ]; then
    trueSource="$(cd "$trueSource"; pwd)"
elif [ -f "$trueSource" ]; then
    if [[ "$trueSource" == */* ]]; then
        trueSource="$(cd "${trueSource%/*}"; pwd)"
    else
        trueSource="$(pwd)"
    fi
fi

declare -a utils=(
   'os'
   'args'
   'fs'
   'io'
   'proxy'
   'strings'
   'system'
   'vcs'
)

for i in ${utils[@]}; do
    [ -f "${trueSource}/utils/utils_${i}" ] \
      && source "${trueSource}/utils/utils_${i}"
done