#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# HTTP Definitions

download() {
    local url="$1"
    local archive="$2"

    if command -v 'curl' &> /dev/null; then
        curl -LksSo "$archive" "$url" &> /dev/null

        return $?
    elif command -v 'wget' &> /dev/null; then
        wget --no-check-certificate -qO "$archive" "$url" &> /dev/null
        return $?
    fi

    return 1
}